name: Docker Image CI

on:
  push:
    branches: [ docker ]
  pull_request:
    branches: [ docker ]

jobs:

  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docker

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag thmho-lidar-node:$(date +%s)
    - uses: actions/checkout@v2
    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ragesh18/thmho-lidar-node
        tags: latest, ${{ github.run_number }}
